// src/services/pdfService.js
import html2pdf from 'html2pdf.js';

export function generateReport(businessInfo, searchData, opportunityData) {
  const reportTemplate = `
    <div class="report">
      <header>
        <h1>${businessInfo.name}</h1>
        <h2>Digital Presence Opportunity Report</h2>
        <p>Generated on: ${new Date().toLocaleDateString()}</p>
      </header>

      <section>
        <h2>Executive Summary</h2>
        <p>Your business is currently missing out on potential customers who are searching online.</p>
        <p>Monthly searches related to your business type in this area: ${searchData.totalMonthlySearches}</p>
        <p>Estimated potential monthly website visitors: ${opportunityData.estimatedMonthlyClicks}</p>
        <p>Estimated potential new customers per month: ${opportunityData.potentialCustomers}</p>
      </section>

      <section>
        <h2>Top Search Keywords</h2>
        <table>
          <tr>
            <th>Keyword</th>
            <th>Monthly Searches</th>
          </tr>
          ${searchData.keywordBreakdown.slice(0, 5).map(kw => `
            <tr>
              <td>${kw.keyword}</td>
              <td>${kw.volume}</td>
            </tr>
          `).join('')}
        </table>
      </section>

      <section>
        <h2>Recommended Actions</h2>
        <ul>
          <li>Create a Google My Business listing for your business</li>
          <li>Add complete business information including hours, photos, and services</li>
          <li>Encourage satisfied customers to leave reviews</li>
          <li>Regularly update your business information</li>
          <li>Post updates about special offers and events</li>
        </ul>
      </section>

      <footer>
        <p>This report was generated by Location Gap Finder. For more information or to implement these recommendations, please contact us.</p>
      </footer>
    </div>
  `;
  
  const element = document.createElement('div');
  element.innerHTML = reportTemplate;
  
  const opt = {
    margin: 10,
    filename: `${businessInfo.name.replace(/\s+/g, '-').toLowerCase()}-report.pdf`,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { scale: 2 },
    jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
  };
  
  return html2pdf().from(element).set(opt).save();
}

export function createPrintableReport(businessInfo, searchData, opportunityData, containerId) {
  // Use the same template as generateReport
  const reportTemplate = generateReport(businessInfo, searchData, opportunityData);
  
  const container = document.getElementById(containerId);
  if (container) {
    container.innerHTML = reportTemplate;
  }
  
  return reportTemplate;
}