// src/services/pdfService.js
import html2pdf from 'html2pdf.js';

export function generateReport(businessInfo, searchData, opportunityData) {
  const reportTemplate = `
    
      
        ${businessInfo.name}
        Digital Presence Opportunity Report
        Generated on: ${new Date().toLocaleDateString()}
      
      
      
        Executive Summary
        Your business is currently missing out on potential customers who are searching online.
        Monthly searches related to your business type in this area: ${searchData.totalMonthlySearches}
        Estimated potential monthly website visitors: ${opportunityData.estimatedMonthlyClicks}
        Estimated potential new customers per month: ${opportunityData.potentialCustomers}
      
      
      
        Top Search Keywords
        
          
            Keyword
            Monthly Searches
          
          ${searchData.keywordBreakdown.slice(0, 5).map(kw => `
            
              ${kw.keyword}
              ${kw.volume}
            
          `).join('')}
        
      
      
      
        Recommended Actions
        
          Create a Google My Business listing for your business
          Add complete business information including hours, photos, and services
          Encourage satisfied customers to leave reviews
          Regularly update your business information
          Post updates about special offers and events
        
      
      
      
        This report was generated by Location Gap Finder. For more information or to implement these recommendations, please contact us.
      
    
  `;
  
  const element = document.createElement('div');
  element.innerHTML = reportTemplate;
  
  const opt = {
    margin: 10,
    filename: `${businessInfo.name.replace(/\s+/g, '-').toLowerCase()}-report.pdf`,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { scale: 2 },
    jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
  };
  
  return html2pdf().from(element).set(opt).save();
}

// Function to create a printable version in the DOM
export function createPrintableReport(businessInfo, searchData, opportunityData, containerId) {
  const reportTemplate = `
    
      
        ${businessInfo.name}
        Digital Presence Opportunity Report
        Generated on: ${new Date().toLocaleDateString()}
      
      
      
        Executive Summary
        Your business is currently missing out on potential customers who are searching online.
        Monthly searches related to your business type in this area: ${searchData.totalMonthlySearches}
        Estimated potential monthly website visitors: ${opportunityData.estimatedMonthlyClicks}
        Estimated potential new customers per month: ${opportunityData.potentialCustomers}
      
      
      
        Top Search Keywords
        
          
            Keyword
            Monthly Searches
          
          ${searchData.keywordBreakdown.slice(0, 5).map(kw => `
            
              ${kw.keyword}
              ${kw.volume}
            
          `).join('')}
        
      
      
      
        Recommended Actions
        
          Create a Google My Business listing for your business
          Add complete business information including hours, photos, and services
          Encourage satisfied customers to leave reviews
          Regularly update your business information
          Post updates about special offers and events
        
      
      
      
        This report was generated by Location Gap Finder. For more information or to implement these recommendations, please contact us.
      
    
  `;
  
  const container = document.getElementById(containerId);
  if (container) {
    container.innerHTML = reportTemplate;
  }
  
  return reportTemplate;
}
```